# Generated by Django 2.2.6 on 2019-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191029_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreateView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('preference1', models.BooleanField(default=False)),
                ('preference2', models.BooleanField(default=False)),
                ('preference3', models.BooleanField(default=False)),
            ],
        ),
    ]
