# Generated by Django 2.2.6 on 2019-10-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preference2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preference3',
        ),
    ]
