# Generated by Django 2.2.6 on 2019-10-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191029_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preference1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Choices'),
        ),
    ]
