# Generated by Django 2.2.6 on 2019-10-29 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191029_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(to='accounts.Choices'),
        ),
    ]
