# Generated by Django 2.2.6 on 2019-10-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
