# Generated by Django 2.2.6 on 2019-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191104_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Preference',
            new_name='Highlight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highlights',
            field=models.ManyToManyField(related_name='highlights', to='accounts.Highlight'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cuisines',
            field=models.ManyToManyField(related_name='cuisines', to='accounts.Cuisine'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='establishmenttypes',
            field=models.ManyToManyField(related_name='establishmenttypes', to='accounts.EstablishmentType'),
        ),
    ]
